export const NEXT_STEP = 'NEXT_STEP '
export const PREV_STEP = 'PREV_STEP'

export const VALIDATE_KEY = 'VALIDATE_KEY'
export const VALIDATE_API = 'VALIDATE_API'

export const INVALIDATE_KEY = 'INVALIDATE_KEY'
export const INVALIDATE_API = 'INVALIDATE_API'

export const VALIDATE_RESULTS = 'VALIDATE_RESULTS'

// export const READY_FOR_NEXT='READY_FOR_NEXT'
//   export const NOT_READY_FOR_NEXT='NOT_READY_FOR_NEXT'
