
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATE_FAILED'
export const UPDATE_REQUEST = 'UPDATE_REQUEST'

export const EDIT_INFORMATION = 'EDIT_EDUCATION'
export const READ_INFORMATION = 'READ_INFORMATION'

export const IS_WRITING = 'IS_WRITING'

export const IS_CHOOSING = 'IS_CHOOSING'

export const INVALIDATE = 'INVALIDATE'
